### ISSUE TITLE
"ls" returns root directory

### ISSUE THREAD

**Issue by egladman** [paradigm/digmbot#2]
`ls` returns the contents of the root directory which in this case is:

```
bin boot dev etc home lib media mnt opt proc root run sbin sys tmp usr var
```

This behavior is not desired.

**Comment by benlk** [comment]
What directory should be returned?

**Comment by egladman** [comment]
I guess the real question is, why does digmbot respond to `ls` in the first place?

**Comment by BenjaminFair** [comment]
Because it's funny

**Comment by moore3071** [comment]
@benlk, preferably the home directory of the BSD jail that the bot is being run from

**Comment by paradigm** [comment]
As far as I know, digmbot does not act as you've described.

My guess is you're referring to some running instance of it which:

- Includes a plugin to make it act this way.  If so, the plugin is not managed
  by this project; at least not at this time.
- A fork to include additional functionality.  Being a fork, it's not this
  project.
- Some other project also calling itself "digmbot".  That'd be another project,
  then, and not here.

If I am mistaken and you can provide steps to reproduce the issue, or show me
the relevant bit of code, I'll be happy to follow up then.  Otherwise, I'm
inclined to close the ticket as "invalid".

**Comment by egladman** [comment]
@paradigm is your digmbot idling in `#osuosc`?

**Comment by benlk** [comment]
For reference, this digmbot:

```
[digmbot] (~digmbot@osuosc/paradigm/bot/digmbot): digmbot
[digmbot] +#osuosc
[digmbot] barjavel.freenode.net (Paris, FR)
[digmbot] idle: 00 hours 41 minutes 49 seconds, signon at: Wed, 02 Mar 2016 21:24:02
[digmbot] is logged in as digmbot
[digmbot] End of /WHOIS list.
```
